version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: carletti_fit_db
    restart: always
    environment:
      POSTGRES_USER: carletti_admin
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: carletti_fit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carletti_admin -d carletti_fit"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: carletti_fit_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@carlettifit.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
