// This file is auto-generated by @hey-api/openapi-ts

export const $Body_login_access_token_api_v1_auth_login_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_access_token_api_v1_auth_login_post'
} as const;

export const $ClientCreate = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password',
            default: 'carlettifit123'
        }
    },
    type: 'object',
    required: ['email', 'full_name'],
    title: 'ClientCreate'
} as const;

export const $ExerciseSetCreate = {
    properties: {
        exercise_id: {
            type: 'integer',
            title: 'Exercise Id'
        },
        reps: {
            type: 'integer',
            title: 'Reps'
        },
        weight_kg: {
            type: 'number',
            title: 'Weight Kg'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        is_completed: {
            type: 'boolean',
            title: 'Is Completed',
            default: false
        }
    },
    type: 'object',
    required: ['exercise_id', 'reps', 'weight_kg', 'order'],
    title: 'ExerciseSetCreate'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $ProfileOut = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        }
    },
    type: 'object',
    title: 'ProfileOut'
} as const;

export const $Tenant = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'slug'],
    title: 'Tenant'
} as const;

export const $Token = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token', 'token_type'],
    title: 'Token'
} as const;

export const $UserOut = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        profile: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProfileOut'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserOut'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $WorkoutCreate = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        intensity: {
            type: 'string',
            title: 'Intensity'
        },
        volume: {
            type: 'string',
            title: 'Volume'
        },
        duration_minutes: {
            type: 'integer',
            title: 'Duration Minutes'
        },
        client_id: {
            type: 'integer',
            title: 'Client Id'
        },
        exercises: {
            items: {
                '$ref': '#/components/schemas/ExerciseSetCreate'
            },
            type: 'array',
            title: 'Exercises',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'intensity', 'volume', 'duration_minutes', 'client_id'],
    title: 'WorkoutCreate'
} as const;

export const $WorkoutOut = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        intensity: {
            type: 'string',
            title: 'Intensity'
        },
        volume: {
            type: 'string',
            title: 'Volume'
        },
        duration_minutes: {
            type: 'integer',
            title: 'Duration Minutes'
        },
        client_id: {
            type: 'integer',
            title: 'Client Id'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        completed: {
            type: 'boolean',
            title: 'Completed'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'intensity', 'volume', 'duration_minutes', 'client_id', 'id', 'completed', 'created_at'],
    title: 'WorkoutOut'
} as const;