// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { ReadUserMeApiV1AuthMeGetError, ReadUserMeApiV1AuthMeGetResponse, LoginAccessTokenApiV1AuthLoginPostData, LoginAccessTokenApiV1AuthLoginPostError, LoginAccessTokenApiV1AuthLoginPostResponse, ReadTenantsApiV1TenantsGetError, ReadTenantsApiV1TenantsGetResponse, CreateClientApiV1ClientsPostData, CreateClientApiV1ClientsPostError, CreateClientApiV1ClientsPostResponse, ListClientsApiV1ClientsGetData, ListClientsApiV1ClientsGetError, ListClientsApiV1ClientsGetResponse, CreateWorkoutApiV1WorkoutsPostData, CreateWorkoutApiV1WorkoutsPostError, CreateWorkoutApiV1WorkoutsPostResponse, ListWorkoutsApiV1WorkoutsGetData, ListWorkoutsApiV1WorkoutsGetError, ListWorkoutsApiV1WorkoutsGetResponse, ListMetricsApiV1MetricsGetError, ListMetricsApiV1MetricsGetResponse, GetNutritionApiV1NutritionGetError, GetNutritionApiV1NutritionGetResponse, GenerateWorkoutApiV1AiGenerateWorkoutPostError, GenerateWorkoutApiV1AiGenerateWorkoutPostResponse, AnalyzeMetricsApiV1AiAnalyzeMetricsPostError, AnalyzeMetricsApiV1AiAnalyzeMetricsPostResponse, ChatbotApiV1AiChatPostError, ChatbotApiV1AiChatPostResponse, ListIntegrationsApiV1IntegrationsGetError, ListIntegrationsApiV1IntegrationsGetResponse, ReadRootGetError, ReadRootGetResponse } from './types.gen';

/**
 * Read User Me
 */
export const readUserMeApiV1AuthMeGet = (options?: Options) => { return (options?.client ?? client).get<ReadUserMeApiV1AuthMeGetResponse, ReadUserMeApiV1AuthMeGetError>({
    ...options,
    url: '/api/v1/auth/me'
}); };

/**
 * Login Access Token
 */
export const loginAccessTokenApiV1AuthLoginPost = (options: Options<LoginAccessTokenApiV1AuthLoginPostData>) => { return (options?.client ?? client).post<LoginAccessTokenApiV1AuthLoginPostResponse, LoginAccessTokenApiV1AuthLoginPostError>({
    ...options,
    url: '/api/v1/auth/login'
}); };

/**
 * Read Tenants
 */
export const readTenantsApiV1TenantsGet = (options?: Options) => { return (options?.client ?? client).get<ReadTenantsApiV1TenantsGetResponse, ReadTenantsApiV1TenantsGetError>({
    ...options,
    url: '/api/v1/tenants/'
}); };

/**
 * Create Client
 */
export const createClientApiV1ClientsPost = (options: Options<CreateClientApiV1ClientsPostData>) => { return (options?.client ?? client).post<CreateClientApiV1ClientsPostResponse, CreateClientApiV1ClientsPostError>({
    ...options,
    url: '/api/v1/clients/'
}); };

/**
 * List Clients
 */
export const listClientsApiV1ClientsGet = (options?: Options<ListClientsApiV1ClientsGetData>) => { return (options?.client ?? client).get<ListClientsApiV1ClientsGetResponse, ListClientsApiV1ClientsGetError>({
    ...options,
    url: '/api/v1/clients/'
}); };

/**
 * Create Workout
 */
export const createWorkoutApiV1WorkoutsPost = (options: Options<CreateWorkoutApiV1WorkoutsPostData>) => { return (options?.client ?? client).post<CreateWorkoutApiV1WorkoutsPostResponse, CreateWorkoutApiV1WorkoutsPostError>({
    ...options,
    url: '/api/v1/workouts/'
}); };

/**
 * List Workouts
 */
export const listWorkoutsApiV1WorkoutsGet = (options?: Options<ListWorkoutsApiV1WorkoutsGetData>) => { return (options?.client ?? client).get<ListWorkoutsApiV1WorkoutsGetResponse, ListWorkoutsApiV1WorkoutsGetError>({
    ...options,
    url: '/api/v1/workouts/'
}); };

/**
 * List Metrics
 */
export const listMetricsApiV1MetricsGet = (options?: Options) => { return (options?.client ?? client).get<ListMetricsApiV1MetricsGetResponse, ListMetricsApiV1MetricsGetError>({
    ...options,
    url: '/api/v1/metrics/'
}); };

/**
 * Get Nutrition
 */
export const getNutritionApiV1NutritionGet = (options?: Options) => { return (options?.client ?? client).get<GetNutritionApiV1NutritionGetResponse, GetNutritionApiV1NutritionGetError>({
    ...options,
    url: '/api/v1/nutrition/'
}); };

/**
 * Generate Workout
 * Geração de planos de treino personalizados via LLM.
 * TODO: Integração com OpenAI/Anthropic.
 */
export const generateWorkoutApiV1AiGenerateWorkoutPost = (options?: Options) => { return (options?.client ?? client).post<GenerateWorkoutApiV1AiGenerateWorkoutPostResponse, GenerateWorkoutApiV1AiGenerateWorkoutPostError>({
    ...options,
    url: '/api/v1/ai/generate-workout'
}); };

/**
 * Analyze Metrics
 * Análise e sugestões baseadas em métricas.
 */
export const analyzeMetricsApiV1AiAnalyzeMetricsPost = (options?: Options) => { return (options?.client ?? client).post<AnalyzeMetricsApiV1AiAnalyzeMetricsPostResponse, AnalyzeMetricsApiV1AiAnalyzeMetricsPostError>({
    ...options,
    url: '/api/v1/ai/analyze-metrics'
}); };

/**
 * Chatbot
 * Chatbot de suporte/coaching.
 */
export const chatbotApiV1AiChatPost = (options?: Options) => { return (options?.client ?? client).post<ChatbotApiV1AiChatPostResponse, ChatbotApiV1AiChatPostError>({
    ...options,
    url: '/api/v1/ai/chat'
}); };

/**
 * List Integrations
 */
export const listIntegrationsApiV1IntegrationsGet = (options?: Options) => { return (options?.client ?? client).get<ListIntegrationsApiV1IntegrationsGetResponse, ListIntegrationsApiV1IntegrationsGetError>({
    ...options,
    url: '/api/v1/integrations/'
}); };

/**
 * Read Root
 */
export const readRootGet = (options?: Options) => { return (options?.client ?? client).get<ReadRootGetResponse, ReadRootGetError>({
    ...options,
    url: '/'
}); };